default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 10).to_i %>
  timeout: <%= ENV.fetch("PG_TIMEOUT_IN_SECONDS", 3).to_i.seconds %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *default
  host: <%= ENV.fetch("PG_HOST") { 'localhost' } %>
  database: <%= ENV.fetch("PG_DATABASE_NAME", "code_fund_ads_development") %>

test:
  <<: *default
  host: <%= ENV.fetch("PG_HOST") { 'localhost' } %>
  database: code_fund_ads_test

production:
  <<: *default
  prepared_statements: false # See https://edgeguides.rubyonrails.org/configuring.html#configuring-a-postgresql-database
  url: <%= ENV["DATABASE_URL"] %>
